export * from "./LandingPage";
export * from "./SectionPage";
export * from "./LoginPage";
export * from "./CategoryPage";
export * from "./ProductPage";
export * from "./SignUpPage";
export * from "./CartPage";
export * from "./CheckOutPage";
export * from "./PersonalInfoPage";
